### ISSUE TITLE
search.class is never set

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-root-admin-template#3]
https://github.com/conedevelopment/sprucecss-root-admin-template/blob/faac5579b4d87fce85f9d3b698512ee16327e185/src/_includes/partial/search.html#L1

Comes from `dataTable.searchClass`

It is always null.
```html
$ grep -r 'form class="search-form'
dist/products/index.html:                                <form class="search-form ">
dist/customers/index.html:                                <form class="search-form ">
dist/orders/index.html:                                <form class="search-form ">
src/_includes/partial/search.html:<form class="search-form {{ search.class }}">
```

Is it null by mistake?

**Comment by adamlaki** [comment]
I will look into it this week, thank you!

**Comment by adamlaki** [comment]
This is intentional. Right now, we don't have (yet) a demo where it is in use. 

Thank you!
