### ISSUE TITLE
Eleventy plugin to change file name based on hash of its content

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-root-admin-template#4]
Current global random hash
`/js/repeater.js?ddbd3ad9-530c-44b3-bef8-58a921959a1a`
👇🏻 hash of the file's content
`/js/repeater.js?e7fd847f7f435b18e64192d282f82c75`
👇🏻 include the hash in the file name, query parameters are error prone
`/js/repeater.e7fd847f7f435b18e64192d282f82c75.js`

Where is that plugin??

- Hashes can be shorter.
- Only the URL of changed files would update.

**Comment by szepeviktor** [comment]
Turns out it is easy.
```js
  config.addPassthroughCopy('./src/js/**', {
    // https://github.com/timkendrick/recursive-copy#usage
    rename: function (filePath) {
      return put hash into filePath;
    }
  });
```

Would you merge a PR with an 8 character long hash in file names?
`/js/repeater.e7fd847f.js`

**Comment by adamlaki** [comment]
Yes Viktor, I would merge shorter file hases. No problem.

**Comment by szepeviktor** [comment]
The clue is that the hash will reflect the file content.
So only changed files will have a new hash!

**Comment by adamlaki** [comment]
Do you think it is possible to watch for changes?

Also, I don't see a simple solution to the passthrough asset renaming. Here is how it works now:

https://github.com/conedevelopment/sprucecss-root-admin-template/blob/main/src/_includes/layout/base.html#L1
https://github.com/conedevelopment/sprucecss-root-admin-template/blob/main/src/_data/global.js

I think this is the simplest solution.

**Comment by szepeviktor** [comment]
There are 2 steps.

1. Change the name of assets: `config.addPassthroughCopy::rename`
2. Change the URL with a filter `{{ '/js/theme-change-assets.js' | contentHash }}`

Both will call the same function.
It will take an extra 0.000001 second as every assets will be hashed twice.

**Comment by adamlaki** [comment]
The steps seem simple, but with our current setup and with 11ty in general, I don't know how to achieve this.

**Comment by szepeviktor** [comment]
I work on it in my secret lair.
PR-s arriving soon.

**Comment by adamlaki** [comment]
We could revert to my transformer solution but I think with Alpine.js this is not that easy.
