### ISSUE TITLE
Greatly improved SVG handling

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-root-admin-template#5]
- Fix html-validate's `attr-quotes` rule: always use double quotes
- Less modules: no himalaya
- Less filters: no "svgIcon"

Example

```njk
{{ '/src/img/icon/minus.svg' | svgContents('btn__icon') | safe }}
```

From https://github.com/conedevelopment/sprucecss-root-admin-template/issues/1#issuecomment-1636710909

Would you merge a PR touching 58 lines?

**Comment by adamlaki** [comment]
Viktor, I don't think that this is a better solution. Also, this solution won't solve our other duplicated ID problem: https://github.com/conedevelopment/sprucecss-root-admin-template/blob/main/.eleventy.js#L9

**Comment by szepeviktor** [comment]
All right.
